'use client';
import {lazy,Suspense,memo,useEffect,useRef,useState} from 'react';
import {SiteHeader} from '@/components/site-header';
import {Switch} from '@/components/ui/switch';
import {PixelIcon,type PixelIconName} from '@/components/pixel-icon';
import {type Live,fresh} from '@/lib/live';
import {useBroadcast} from '@/lib/use-broadcast';
import {useLiveTools} from '@/lib/use-live-tools';
import {LiveMemory} from '@/components/live-memory';
const FlySpectator=lazy(()=>import('@/components/fly-spectator').catch(()=>({default:()=> <p className="spectator-notice">Could not load 3D. Reload the page to try again.</p>})));
const formatter=new Intl.NumberFormat('en-US');
const number=(x:number)=>formatter.format(x);
const Raster=memo(function Raster({data}:{data:Live}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=ref.current?.getContext('2d');if(!c)return;c.clearRect(0,0,800,256);
 const bins=data.raster.bins;if(!bins.length)return;
 const begin=bins[0].neural_ms-bins[0].window_ms,end=bins[bins.length-1].neural_ms,span=Math.max(.1,end-begin);
 for(const bin of bins)bin.counts.forEach((n,row)=>{if(n){c.fillStyle='#fff';c.globalAlpha=Math.min(n/(bin.window_ms/1000)/200,1);c.fillRect((bin.neural_ms-bin.window_ms-begin)/span*800,row*2,Math.max(1,bin.window_ms/span*800),2)}});c.globalAlpha=1;
 },[data]);
 const bins=data.raster.bins;const seconds=bins.length?(bins[bins.length-1].neural_ms-bins[0].neural_ms+bins[0].window_ms)/1000:0;
 return <><canvas ref={ref} width={800} height={256} className="raster" aria-label="Binned simulated firing rates for 128 fixed sampled neurons. Horizontal widths represent elapsed neural time; white represents 200 spikes per second or above."/><div className="plot-key"><span>128 sampled cells</span><span>{seconds.toFixed(2)} s brain time →</span><span>0–200 Hz</span></div></>;
});
const Retina=memo(function Retina({data}:{data:Live}){return <><svg className="retina" viewBox="0 0 500 230" role="img" aria-label="Raw frame luminance at inferred receptor sample locations. Both eye projections overlap; this is not neuron firing or a calibrated view through fly eyes."><rect width="500" height="230" fill="#000"/>{data.retina.uv.map(([x,y],i)=>{const v=Math.round(255*Math.pow(data.retina.luminance[i],1/2.2));return <rect key={i} x={8+x*480} y={8+y*210} width="4" height="4" fill={`rgb(${v},${v},${v})`}/>})}</svg><div className="plot-key"><span>Frame brightness</span><span>{number(data.retina.full_sample_count)} R1–R6 inputs · 1 in 8 shown</span><span>0–1</span></div></>});
function Control({icon,label,value,active}:{icon:PixelIconName;label:string;value:string;active:boolean}){return <div className={`control-key ${active?'is-active':''}`}><PixelIcon name={icon}/><span>{label}</span><strong>{value}</strong></div>}
export default function LiveDoom(){
 const {data,error,now}=useBroadcast();
 const [spectator,setSpectator]=useState(false);
 const [retina,setRetina]=useState(true);const [activity,setActivity]=useState(true);
 const live=fresh(data,now)&&!error;const bci=data?.decoder==='bci';
 const mapping=(type:string)=>bci?(type==='DNp20'?'R − L → turn':type==='DNpe017'?'Rate → move; spike → fire':type==='PPL101'?'Reinforcement readout':type==='MBON11'?'Memory output readout':'Biological comparison'):(type==='DNa02'?'R − L → turn':type==='DNp09'?'Forward':type==='MDN'?'Backward':type==='MN9'?'Spike → fire':'Visual comparison');
 const observation=()=>({status:live?'live':'offline',run_id:data?.run_id??null,sequence:data?.sequence??null,condition:data?.condition??null,decoder:data?.decoder??null,clocks:data?.clocks??null,action:data?.action??null,readouts:data?.readouts??[],learning:data?.learning??null,overlays:{retina,activity},model:{dataset:'MaleCNS v1.0',full_graph:true,validated_vision:false,plasticity:!!data?.learning?.enabled},broadcast_depends_on_host:true});
 useLiveTools(observation,(r,a)=>{setRetina(r);setActivity(a)});
 return <main className="arcade live-page">
  <a className="skip-link" href="#game">Skip to live game</a>
  <SiteHeader page="home"/>
  <section className="cabinet" aria-label="Live neural Doom experiment">
   <div className="game-column" id="game">
    <div className="window-bar"><span><PixelIcon name="screen"/> DOOM.EXE<span className={`game-status ${live?'is-live':''}`} role="img" aria-label={live?'Broadcast live':'Broadcast offline'} title={live?'Broadcast live':'Broadcast offline'}/></span><span className="frame-meta">ROUND {data?String(data.game.episode).padStart(2,'0'):'—'} <span className="meta-separator">/</span> FRAME {data?number(data.sequence):'—'}</span></div>
    <div className="view-selector"><span>VIEW</span><button type="button" aria-pressed={!spectator} onClick={()=>setSpectator(false)}>DOOM POV</button><button type="button" aria-pressed={spectator} onClick={()=>setSpectator(true)}>3D FLY / CAMERA</button></div>
    {spectator?<Suspense fallback={<div className="screen-placeholder">LOADING 3D…</div>}><FlySpectator data={data} live={live}/></Suspense>:<div className="screen">{data?<img src={data.frame} width={640} height={480} alt="Live Doom frame supplied to the modeled fly visual system"/>:<div className="screen-placeholder"><PixelIcon name="signal"/><h2>NO SIGNAL</h2><p>{error}</p></div>}
     {data&&!live?<div className="offline-overlay"><PixelIcon name="signal"/><strong>SIGNAL LOST</strong><span>Last frame · {new Date(data.generated_at_ms).toLocaleTimeString()}</span><span>Waiting for the simulation host</span></div>:null}
    </div>}
   </div>
   <aside className="live-telemetry" aria-label="Live game statistics and neural controls">
    <div className="telemetry-heading"><span>LIVE TELEMETRY</span><PixelIcon name="signal"/></div>
    {data&&!live?<p className="telemetry-stale">LAST RECEIVED VALUES</p>:null}
    <div className="hud-vitals" aria-label="Doom statistics"><div><span><PixelIcon name="heart"/>HEALTH</span><strong>{data?.game.health??'—'}</strong></div><div><span><PixelIcon name="skull"/>KILLS</span><strong>{data?.game.kills??'—'}</strong></div><div><span><PixelIcon name="ammo"/>AMMO</span><strong>{data?.game.ammo??'—'}</strong></div></div>
    {data?.protocol.scenario==='combat_survival'?<div className="hud-arena" aria-label="Survival arena"><span><PixelIcon name="skull"/> ENEMIES <strong>{data.game.enemies??'—'}</strong></span><span title="Time alive this round, in game seconds">ALIVE <strong>{(data.game.tick/35).toFixed(1)} s</strong></span></div>:null}
    <div className="hud-clocks"><div><span>SPEED</span><strong>{data?`${data.clocks.speed.toFixed(2)}×`:'—'}</strong></div><div><span>BRAIN TIME</span><strong>{data?data.clocks.neural_seconds.toFixed(1):'—'}<small> s</small></strong></div></div>
    <div className="hud-controls-heading">NEURON → BUTTON</div>
    <div className="hud-controls"><Control icon="turn" label="TURN" value={data?data.action.turn.toFixed(2):'—'} active={live&&!!data&&Math.abs(data.action.turn)>.01}/><Control icon="move" label="MOVE" value={data?data.action.forward.toFixed(2):'—'} active={live&&!!data&&Math.abs(data.action.forward)>.01}/><Control icon="target" label="FIRE" value={data?(data.action.attack?'ON':'OFF'):'—'} active={live&&!!data?.action.attack}/></div>
    <div className="hud-model"><span>{data?.learning?'EXPERIMENTAL / UNVALIDATED':data?(bci?'EXPERIMENTAL BCI':'ROLE COMPARISON'):'NEURAL EXPERIMENT'}</span><span>{data?.learning?.enabled?'TRAINING ON':data?.learning?'FROZEN CONTROL':'NO LEARNING'}</span></div>
   </aside>
  </section>
  <section className="inspection" aria-label="Inspect neural signals"><div className="inspection-toolbar"><h2>LOOK INSIDE</h2><div className="toggles"><label htmlFor="retina"><PixelIcon name="eye"/> EYES</label><Switch id="retina" className="pixel-switch" checked={retina} onCheckedChange={setRetina}/><label htmlFor="activity"><PixelIcon name="brain"/> BRAIN</label><Switch id="activity" className="pixel-switch" checked={activity} onCheckedChange={setActivity}/></div></div>
   <div className="signals">{retina?<section className="signal-panel"><div className="panel-heading"><h3><PixelIcon name="eye"/><span>01 / SENSORY INPUT</span></h3><span className="panel-caption">LIVE PIXELS</span></div>{data?<Retina data={data}/>:<div className="empty-plot">Waiting for retinal input</div>}</section>:null}{activity?<section className="signal-panel"><div className="panel-heading"><h3><PixelIcon name="brain"/><span>02 / NEURAL ACTIVITY</span></h3><span className="panel-caption">{data?`${number(data.window_spikes)} SPIKES`:'—'}</span></div>{data?<Raster data={data}/>:<div className="empty-plot">Waiting for neural activity</div>}</section>:null}</div>
  </section>
  {data?.learning?<LiveMemory data={data} live={live}/>:null}
  <details className="disclosure"><summary><span><PixelIcon name="signal"/> NEURON READOUTS</span><span className="summary-end"><span>{data?.readouts.length??'—'} CELLS</span><PixelIcon name="plus"/></span></summary><div className="disclosure-body"><p className="detail-intro">Fixed readouts of modeled activity. These are engineered game controls, not validated natural fly commands.</p><div className="table-scroll"><table><thead><tr><th>Cell</th><th>ID</th><th>Side</th><th>Spikes</th><th>Rate</th><th>Mapping</th></tr></thead><tbody>{data?.readouts.slice().sort((a,b)=>bci?Number(['DNp20','DNpe017'].includes(b.type))-Number(['DNp20','DNpe017'].includes(a.type)):0).map(r=><tr key={r.id}><td>{r.type}</td><td>{r.id}</td><td>{r.side==='L'?'L':'R'}</td><td>{r.spikes}</td><td><div className="rate"><span style={{width:`${Math.min(100,r.rate_hz)}%`}}/><code>{r.rate_hz.toFixed(1)} Hz</code></div></td><td>{mapping(r.type)}</td></tr>)??<tr><td colSpan={6}>Waiting for readouts.</td></tr>}</tbody></table></div><p className="detail-intro">{data?`${data.protocol.dt_ms} ms timesteps · ${number(data.total_spikes)} total spikes · ${number(data.total_action_ticks)} action ticks.`:'100 ms rate filter.'}</p></div></details>
  <details className="disclosure" id="experiment-notes"><summary><span><PixelIcon name="code"/> EXPERIMENT NOTES</span><span className="summary-end"><span>METHOD + SOURCE</span><PixelIcon name="plus"/></span></summary><div className="disclosure-body"><div className="notes-grid">
   <section><h3>THE CONNECTION</h3><p>Live game pixels → inferred retinal inputs → the full retained MaleCNS v1.0 graph → fixed game controls. 25,582,938 connections; 124,177,617 synaptic contacts.</p><p>DNp20 difference turns. DNpe017 rate moves; a spike fires. These four cells were chosen after visual-response calibration. Biological walking and mouthpart readouts remain visible as a comparison; they were silent in the initial test. No enemy coordinates, navigation policy or additional aiming policy enters the decoder. Native game weapon rules remain in Doom.</p></section>
   <section><h3>THE APPROXIMATION</h3><p>This is reconstructed wiring with approximate neuron dynamics, not a validated fly emulation. Visual cells that use graded signals are modeled with a coarse spiking proxy. Retinal geometry, brightness response and tonic lamina current are assumed. The historical baseline produced controls with black input. The training candidate adds inferred R8 color input, KC adaptation and modeled chemical modulation; useful vision remains unvalidated.</p><p>42 unmapped photoreceptors remain in the graph. 3,718 transmitter signs are uncertain. Female BANC retinal mapping is unresolved; this run uses one male reconstruction.</p></section>
   <section><h3>{data?.learning?'MEMORY / EXPERIMENTAL':'REWARD / OFF'}</h3>{data?.learning?<><p>Nonfatal damage schedules 200 ms of engineered current into two PPL101 dopamine cells. Their actual spikes and Kenyon-cell activity drive a modeled plasticity rule on 4,184 existing KC→MBON11 connections. The game never directly changes weights or chooses buttons.</p><p>Terminal damage is excluded; pending feedback ends at round reset. Fast neural state and memory continue across rounds. The earlier candidate failed conditioning and useful-vision checks. Training is running; learned survival is unproven.</p><a href="/live-training.json">Exact training protocol ↗</a></>:<p>The baseline has fixed synapses. Stimulus delivery alone does not establish learning.</p>}</section>
   <section><h3>THE ARENA</h3><p>The combat arena starts with four ranged monsters. Every three game seconds, another can spawn, up to four imps and four bullet-firing zombies. Each type has its own cap so slow survivors can’t block the other type’s replacements. Ammo boxes refill on contact and return eight seconds after collection; dead monsters also drop ammo. Death restarts the arena with 100 bullets. No round timer.</p><p>These are game rules, not fly behaviors. Neural activity continues across rounds. In experimental training, memory efficacies also persist; the other connection strengths stay fixed. Arena v2 fixes a circling stalemate in v1; their results stay separate. <a href="/combat-arena.json" target="_blank" rel="noreferrer">Inspect arena rules ↗</a></p></section>
   <section><h3>THE CLOCK</h3><p>1× means simulation time matches wall time. Doom slows with the brain; no neural steps are skipped. All viewers watch one shared run and cannot control it.</p><p>The viewer buffers about 2.5 seconds of actual frames, capped at eight captures per wall second. Original capture timing is preserved; no frames or neural signals are invented. Enemy counts include monsters outside the camera view. The host must stay online.</p>{data?.protocol.recovery?<p>Recovered neural state. This run began with a fresh arena; the interrupted round is excluded from survival comparisons.</p>:null}<p><a href="/live-profile.json" target="_blank" rel="noreferrer">Live configuration ↗</a></p></section>
   </div><nav className="source-links" aria-label="Experiment documentation"><a href="/review">Scientific audit ↗</a><a href="/audit-experiments.json" target="_blank" rel="noreferrer">Audited experiments ↗</a><a href="/methods.json" target="_blank" rel="noreferrer">Parameters ↗</a><a href="/bci-validation.json" target="_blank" rel="noreferrer">Legacy BCI checks ↗</a><a href="/validation.json" target="_blank" rel="noreferrer">Legacy control experiments ↗</a><a href="https://github.com/nftechie/doomfly" target="_blank" rel="noopener noreferrer"><PixelIcon name="code"/> GitHub source</a><a href="https://elifesciences.org/articles/102230" target="_blank" rel="noreferrer">Steering evidence ↗</a><a href="https://www.nature.com/articles/s41586-024-07523-9" target="_blank" rel="noreferrer">Descending-neuron evidence ↗</a></nav>
   <details className="audit"><summary>INSPECT THIS STEP <PixelIcon name="plus"/></summary><p>Raw RGB, input and spike hashes accompany this step’s controls. The displayed JPEG is compressed from the pre-action frame; game counters are post-action. Stimulation applied and scheduled are distinguished.</p><pre>{data?JSON.stringify(data.audit,null,2):'No live audit step available.'}</pre></details>
  </div></details>
  <footer><span><PixelIcon name="signal"/> ONE SHARED LIVE RUN</span><span>Buffered live · 8 FPS capture cap · host must stay online</span></footer>
 </main>;
}
